feat: allow specifying custom color map
ayonious/console-table-printer pull request #394
Opened 2021-08-11 03:13 UTC by ejose19

## 👀What is this pr about?

Allow specifying a custom color map, in case the user want to use other colors other than the defaults, or disable colors completely by passing an empty object

### Added

- [x] Allow changing the color map

## 👶 The naming of the PR

feat: allow specifying custom color map

2021-10-02 16:54 UTC, ejose19 commented
@ayonious I've resolved the conflicts after #396 was merged.

2022-03-31 12:13 UTC, ayonious requested changes

2022-03-31 12:13 UTC, ayonious requested changes
Also please add at least one test on how to use this.

2022-03-31 14:39 UTC, ayonious commented on index.ts
> +export { Table, printTable, renderTable, COLOR, ALIGNMENT, ColorMap, DEFAULT_COLOR_MAP };
Maybe DEFAULT_COLOR_MAP also is not needed?

2022-04-03 09:04 UTC, ayonious commented
I will add the tests later in another PR.

2022-04-03 09:05 UTC, merged

2022-04-03 11:45 UTC, ayonious commented
:tada: This PR is included in version 2.11.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/console-table-printer/v/2.11.0)
- [GitHub release](https://github.com/ayonious/console-table-printer/releases/tag/v2.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: